# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputTimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredObjID', models.IntegerField(unique=True)),
                ('registeredObjName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.CharField(max_length=200, unique=True)),
                ('taskName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predefinedObjID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RegisteredObjects')),
                ('predefinedTaskName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.TaskList')),
            ],
        ),
        migrations.AddField(
            model_name='activeobjects',
            name='activeObjID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RegisteredObjects'),
        ),
        migrations.AlterUniqueTogether(
            name='taskobjects',
            unique_together=set([('predefinedTaskName', 'predefinedObjID')]),
        ),
    ]
