# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredobjects',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='id',
        ),
        migrations.AlterField(
            model_name='registeredobjects',
            name='registeredObjID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='timeStamp',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
