# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20161102_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredobjects',
            name='registeredObjID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='timeStamp',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
