# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20161103_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskobjects',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activeobjects',
            name='activeObjID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RegisteredObjects'),
        ),
        migrations.AlterField(
            model_name='activeobjects',
            name='inputTimeStamp',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='timeStamp',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='taskobjects',
            name='predefinedObjID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RegisteredObjects'),
        ),
    ]
