# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20161103_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='id',
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='timeStamp',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
