# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20161103_1941'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskobjects',
            unique_together=set([]),
        ),
    ]
