# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20161104_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeobjects',
            name='activeObjID',
        ),
        migrations.DeleteModel(
            name='ActiveObjects',
        ),
    ]
