# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20161104_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredobjects',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registeredobjects',
            name='registeredObjID',
            field=models.IntegerField(unique=True),
        ),
    ]
