# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20161104_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredobjects',
            name='id',
        ),
        migrations.AlterField(
            model_name='registeredobjects',
            name='registeredObjID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
