# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20161104_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskobjects',
            name='predefinedObjID',
        ),
        migrations.DeleteModel(
            name='RegisteredObjects',
        ),
    ]
