# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20161104_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredObjects',
            fields=[
                ('registeredObjID', models.IntegerField(primary_key=True, serialize=False)),
                ('registeredObjName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='taskobjects',
            name='predefinedObjID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.RegisteredObjects'),
            preserve_default=False,
        ),
    ]
