# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20161105_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredObjects',
            fields=[
                ('registeredObjID', models.IntegerField(primary_key=True, serialize=False)),
                ('registeredObjName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predefinedObjID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RegisteredObjects')),
                ('predefinedTaskName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.TaskList')),
            ],
        ),
    ]
