# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_registeredobjects_taskobjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskobjects',
            name='predefinedObjID',
        ),
        migrations.RemoveField(
            model_name='taskobjects',
            name='predefinedTaskName',
        ),
        migrations.DeleteModel(
            name='TaskObjects',
        ),
    ]
