# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20161105_1909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredObjects1',
            new_name='RegisteredObjects',
        ),
        migrations.RenameModel(
            old_name='TaskList1',
            new_name='TaskList',
        ),
        migrations.RenameModel(
            old_name='TaskObjects1',
            new_name='TaskObjects',
        ),
    ]
