# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20161105_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskobjects1',
            name='predefinedObjID',
        ),
        migrations.RemoveField(
            model_name='taskobjects1',
            name='predefinedTaskName',
        ),
        migrations.DeleteModel(
            name='RegisteredObjects1',
        ),
        migrations.DeleteModel(
            name='TaskList1',
        ),
        migrations.DeleteModel(
            name='TaskObjects1',
        ),
    ]
