# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0021_auto_20161105_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredObjects1',
            fields=[
                ('registeredObjID', models.IntegerField(primary_key=True, serialize=False)),
                ('registeredObjName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList1',
            fields=[
                ('timeStamp', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskObjects1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predefinedObjID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RegisteredObjects1')),
                ('predefinedTaskName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.TaskList1')),
            ],
        ),
    ]
