# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_registeredobjects1_tasklist1_taskobjects1'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredObjects',
            fields=[
                ('registeredObjID', models.IntegerField(primary_key=True, serialize=False)),
                ('registeredObjName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('timeStamp', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predefinedObjID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RegisteredObjects')),
                ('predefinedTaskName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.TaskList')),
            ],
        ),
        migrations.RemoveField(
            model_name='taskobjects1',
            name='predefinedObjID',
        ),
        migrations.RemoveField(
            model_name='taskobjects1',
            name='predefinedTaskName',
        ),
        migrations.DeleteModel(
            name='RegisteredObjects1',
        ),
        migrations.DeleteModel(
            name='TaskList1',
        ),
        migrations.DeleteModel(
            name='TaskObjects1',
        ),
    ]
