# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-06 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20161105_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredObjects',
            new_name='RegisteredObject',
        ),
        migrations.RenameModel(
            old_name='TaskObjects',
            new_name='TaskObject',
        ),
    ]
